### ISSUE TITLE
[tts] tts get voices invalid auth

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#600]
```
FirebaseFunctionsException ([firebase_functions/permission-denied] invalid auth

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:23:24)
<asynchronous suspension>
#3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:49:37)
<asynchronous suspension>
#4      TtsModel.getVoices (package:rtchat/models/tts.dart:70:24)
<asynchronous suspension>
)
```

It looks like `getVoices` is called even if I don't have cloud tts enabled?

**Comment by cswills** [comment]
This is fixed in #599
